name: sayohat
description: "Application to share ride."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.2.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  string_validator: ^1.2.0
  flutter_typeahead: ^5.2.0
  yandex_mapkit: ^4.1.0
  flutter_native_splash: ^2.4.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launch-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/map-background.jpeg
    - assets/images/test_ava.JPG
  fonts: 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Comfortaa
      fonts: 
        - asset: assets/fonts/Comfortaa-Light.ttf
  generate: true

scripts:
  test:all: flutter test test/unit_tests/ && flutter test integration_tests/
  test:unit: flutter test test/unit_tests/
  test:integration: flutter test integration_tests/
