.job_prerequisites: &job_prerequisites
  image: "python:latest"

code-style-linting:
  <<: *job_prerequisites
  stage: .pre
  script:
    - pip install pycodestyle
    - python backend/testing/linter.py

backend-test:
  <<: *job_prerequisites
  stage: test
  script:
    - pip install -r backend/auto_settings/requirements.txt
    - echo "This will be replaced with Python tests"

frontend-test:
  stage: test
  script:
    - echo "This will be replaced with Dart tests"
