.python_preparations: &python_preparations
  image: "python:latest"

.flutter_preparations: &flutter_preparations
  image: "instrumentisto/flutter:latest"

code-style-linting:
  <<: *python_preparations
  stage: .pre
  script:
    - pip install pycodestyle
    - python backend/test/linter.py

backend-test:
  <<: *python_preparations
  stage: test
  script:
    - pip install -r backend/auto_settings/requirements.txt
    - echo "Here tests will be run"

frontend-test:
  <<: *flutter_preparations
  stage: test
  script:
    - cd frontend
    - flutter test test/unit_tests/
