services:
  api:
    container_name: fastapi
    build: ..
    restart: always
    ports:
      - 8000:8000
  mongo:
    container_name: mongodatabase
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_hoarder:/data/db
volumes:
  mongodb_hoarder:

