services:
  api:
    container_name: hamsafarapi
    build:
      context: ..
      dockerfile: auto_settings/Dockerfile
    restart: always
    ports:
      - 8000:8000
  mongo:
    container_name: mongodatabase
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_hoarder:/data/db
volumes:
  mongodb_hoarder:

